language: php
php:
  #- 5.4
  - 5.6
  #- 7.0

git:
  depth: 5

before_install:
  - composer self-update

install:
  - composer install

script:
  - composer validate --no-interaction
  - composer test

#End.
