language: php
php:
  #- 5.4
  - 5.6
  #- 7.0

git:
  depth: 20

before_install:
  - git fetch --tags
  - composer self-update

install:
  - composer install

script:
  - composer validate --no-interaction
  - composer test

after_script:
  - git --version
  - git tag
  - git branch
  - git symbolic-ref --short HEAD
  - git describe --tags --long
  - cat .git/config

#End.
